### ISSUE TITLE
Can't be built

### ISSUE THREAD

**Issue by ctkqiang** [sutogan4ik/Android-BLE-GATT-Master-Slave#3]
ERROR: Unsupported method: GradleProject.getProjectDirectory().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

**Comment by a442509097** [comment]
Just only copy the app folder to new empty project folder overlay it...

**Comment by ctkqiang** [comment]
ok, thats a witchcraft. It just worked
